default-hostname
*** Reading remote logs from Cloud Logging.
[2025-05-15, 16:32:44 UTC] {local_task_job_runner.py:123} ▼ Pre task execution logs
[2025-05-15, 16:32:44 UTC] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gudv_nw_research_assistant_nqes_site_daily_norm.source_check manual__2025-05-15T16:32:38.080306+00:00 [queued]>
[2025-05-15, 16:32:44 UTC] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gudv_nw_research_assistant_nqes_site_daily_norm.source_check manual__2025-05-15T16:32:38.080306+00:00 [queued]>
[2025-05-15, 16:32:44 UTC] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-05-15, 16:32:44 UTC] {taskinstance.py:2890} INFO - Executing <Task(BigQueryInsertJobOperator): source_check> on 2025-05-15 16:32:38.080306+00:00
[2025-05-15, 16:32:44 UTC] {standard_task_runner.py:72} INFO - Started process 119013 to run task
[2025-05-15, 16:32:44 UTC] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'gudv_nw_research_assistant_nqes_site_daily_norm', 'source_check', 'manual__2025-05-15T16:32:38.080306+00:00', '--job-id', '851219', '--raw', '--subdir', 'DAGS_FOLDER/vz-it-gudv-dtwndo-0/nqes_site/python/gudv_nqes_site.py', '--cfg-path', '/tmp/tmpeiav44_k']
[2025-05-15, 16:32:44 UTC] {standard_task_runner.py:105} INFO - Job 851219: Subtask source_check
[2025-05-15, 16:32:44 UTC] {task_command.py:473} INFO - Running <TaskInstance: gudv_nw_research_assistant_nqes_site_daily_norm.source_check manual__2025-05-15T16:32:38.080306+00:00 [running]> on host airflow-worker-rg4td
[2025-05-15, 16:32:45 UTC] {abstractoperator.py:778} ERROR - Exception rendering Jinja template for task 'source_check', field 'configuration'. Template: {'query': {'query': "\n    SELECT COUNT(*) AS status_check\n    FROM vz-it-pr-fjpv-mlopdo-0.mlops_curated_tbls_v.run_dt_cntrl_tbl_v2\n    WHERE process_nm IN ('ETL_NTWK_DMA_NQES_SITE')\n    AND status = 'COMPLETE'\n    AND run_dt = '{{ trans_date }}'\n", 'useLegacySql': False}}
Traceback (most recent call last):
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 770, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 185, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 185, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 185, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 185, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 171, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 725, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 127, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/utils/helpers.py", line 301, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/utils/helpers.py", line 296, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 13, in root
  File "/opt/python3.11/lib/python3.11/site-packages/jinja2/runtime.py", line 857, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'trans_date' is undefined
[2025-05-15, 16:32:45 UTC] {taskinstance.py:3312} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3116, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3536, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 1439, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 770, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 185, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 185, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 185, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 185, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 171, in render_template
    return self._render(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/models/abstractoperator.py", line 725, in _render
    return super()._render(template, context, dag=dag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/template/templater.py", line 127, in _render
    return render_template_to_string(template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/utils/helpers.py", line 301, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/airflow/utils/helpers.py", line 296, in render_template
    return "".join(nodes)
           ^^^^^^^^^^^^^^
  File "<template>", line 13, in root
  File "/opt/python3.11/lib/python3.11/site-packages/jinja2/runtime.py", line 857, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'trans_date' is undefined
[2025-05-15, 16:32:45 UTC] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=gudv_nw_research_assistant_nqes_site_daily_norm, task_id=source_check, run_id=manual__2025-05-15T16:32:38.080306+00:00, execution_date=20250515T163238, start_date=20250515T163244, end_date=20250515T163245
[2025-05-15, 16:32:45 UTC] {taskinstance.py:340} ▶ Post task execution logs
